version: "3.8"
services:
  frontend:
    image: datahog-frontend-build:latest
    ports:
      - 4200:4200
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - backend
    command: node_modules/.bin/ng serve --host 0.0.0.0 --poll 2000
  backend:
    image: datahog-backend-build:latest
    ports:
      - 8080:8080
    working_dir: /backend
    environment: 
      - FLYWAY_USER=$FLYWAY_USER 
      - FLYWAY_PASSWORD=$FLYWAY_PASSWORD 
    volumes:
      - ./backend/src:/backend/src
      - ./backend/target:/backend/target
      - ./backend/db:/backend/db
      - ./backend/flyway-migrations.conf:/backend/flyway-migrations.conf
      - ./backend/start-dev.sh:/backend/start-dev.sh
    depends_on:
      - db
    command: bash start-dev.sh
  db: 
    image: postgres:13.1
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - FLYWAY_USER=$FLYWAY_USER 
      - FLYWAY_PASSWORD=$FLYWAY_PASSWORD 
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data/pgdata
      - ./db/initdb:/docker-entrypoint-initdb.d