version: "3.8"
services:
  frontend:
    image: datahog-frontend-build:latest
    ports:
      - 4200:4200
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - backend
    command: node_modules/.bin/ng serve --host 0.0.0.0 --poll 2000
  backend:
    image: datahog-backend-build:latest
    ports:
      - 8080:8080
    volumes:
      - ./backend/src:/backend/src
      - ./backend/target:/backend/target
    command: mvn spring-boot:run