REVOKE ALL
	ON ALL TABLES 
	IN SCHEMA dbo
	FROM PUBLIC;

GRANT USAGE ON SCHEMA dbo
	TO ${PAGEHOG_DB_RUNTIME_USER};

GRANT SELECT, INSERT, UPDATE, DELETE
	ON ALL TABLES 
	IN SCHEMA dbo
	TO ${PAGEHOG_DB_RUNTIME_USER};

ALTER DEFAULT PRIVILEGES 
	FOR ROLE ${PAGEHOG_DB_RUNTIME_USER}
	IN SCHEMA dbo
	GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PAGEHOG_DB_RUNTIME_USER};
