#!/bin/bash -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	-- Create the database
	CREATE DATABASE pagehog WITH
		ENCODING = 'UTF8'
		LC_COLLATE = 'en_US.UTF-8'
		LC_CTYPE = 'en_US.UTF-8'
		TEMPLATE template0;

	-- Create the runtime user for migrations
	CREATE USER $FLYWAY_USER WITH PASSWORD '$FLYWAY_PASSWORD' CREATEDB CREATEROLE;
	GRANT ALL PRIVILEGES ON DATABASE pagehog TO $FLYWAY_USER;

	-- Create the app runtime user
	CREATE USER $PAGEHOG_DB_RUNTIME_USER 
		WITH PASSWORD '$PAGEHOG_DB_RUNTIME_PASSWORD';

	GRANT $PAGEHOG_DB_RUNTIME_USER TO $FLYWAY_USER;

EOSQL