#!/bin/bash -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE pagehog WITH
		ENCODING = 'UTF8'
		LC_COLLATE = 'en_US.UTF-8'
		LC_CTYPE = 'en_US.UTF-8'
		TEMPLATE template0;

	CREATE USER $FLYWAY_USER WITH PASSWORD '$FLYWAY_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE pagehog TO $FLYWAY_USER;
EOSQL